<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vent.Repositories\Vent.Repositories.csproj" />
    <ProjectReference Include="..\Vent.Shared\Vent.Shared.csproj" />
  </ItemGroup>

</Project>
